apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: rcc-manager

images:
- name: williambr2022/rcc-londrina-front
  newName: williambr2022/rcc-londrina-front
  newTag: 86fb9f67cb573e2b201f881fd29b568a5b4b6b3e
