apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: rcc-manager

images:
- name: williambr2022/rcc-londrina-front
  newName: williambr2022/rcc-londrina-front
  newTag: ad043a17e5b4d80830187c8b41800251815f7e6d
