apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: rcc-manager

images:
- name: rcc-lda-front
  newName: williambr2022/rcc-lda-front
  newTag: 8875646651314a3c79e74702d4c0d7bcd11c9b12
