apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: rcc-manager

images:
- name: rcc-londrina-front
  newName: williambr2022/rcc-londrina-front
  newTag: d1da49751844fd2c02c1d4c0229bc2293b966e48
- name: williambr2022/rcc-londrina-front
  newName: williambr2022/rcc-londrina-front
  newTag: 6a63260d417b62a7741b6700876f3a61016aa7ba
