name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: build image and push to docker hub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USER }}/rcc-lda
        tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build   
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: kustomize
        uses: imranismail/setup-kustomize@v2

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image rcc-lda-front=williambr2022/rcc-lda-front:${{ github.sha }}
          cat kustomization.yaml
      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
          git push
      - name: push
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: ${{ github.ref }}